	SELECT COUPONNUM, COUPONNAME, COUPONPERCENT, TO_CHAR(COUPONENDDATE, 'YYYY-MM-DD')COUPONENDDATE
	FROM coupon
	WHERE couponName Like '%'||''||'%'
	ORDER BY COUPONNUM;
	

INSERT INTO COUPON VALUES (
	'CP'|| coupon_seq.NEXTVAL,
	'[10주년 이벤트 당첨자]30% 할인 쿠폰',
	30,
	to_date('2023-04-02','YYYY-MM-DD')
);
INSERT INTO COUPON VALUES (
	'CP'|| coupon_seq.NEXTVAL,
	#{couponName},
	#{couponPercent},
	to_date(#{couponEndDate},'YYYY-MM-DD')
);

SELECT * FROM HAVECOUPON;
SELECT * FROM ORDERDETAILS;
SELECT * FROM PRODUCTS;
SELECT * FROM SHPPINGBASKET;
SELECT * FROM GAINMEMBER;

INSERT INTO SHPPINGBASKET VALUES ('himan','P1');

-- 장바구니 조회
SELECT s.PRODNUM, p.PRODNAME, p.PRODPRICE, p.PRODIMG, p.BRANDNUM 
FROM PRODUCTS p, SHPPINGBASKET s 
WHERE p.PRODNUM = s.PRODNUM
AND s.id = '';

